<template>
  <t-loading :loading="loading"><t-form class="base-form" :data="formData" :rules="FORM_RULES" label-align="top" :label-width="100" @keydown.enter.prevent @reset="onReset" @submit="onSubmit"><div class="form-basic-container"><div class="form-basic-item"><div class="form-basic-container-title">{{ formData.id ? '编辑换电订单' : '新建换电订单' }}</div><p class="form-tip">用于处理换电、暂存和电池租赁的业务记录。</p><t-row class="row-gap" :gutter="[32, 24]">
    <t-col :xs="12" :lg="6"><t-form-item label="订单号" name="orderNo"><t-input v-model="formData.orderNo" :maxlength="50" placeholder="请输入订单号" /></t-form-item></t-col>
    <t-col :xs="12" :lg="6"><t-form-item label="用户 ID" name="userId"><t-input-number v-model="formData.userId" :min="1" placeholder="请输入用户 ID" /></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="站点 ID" name="stationId"><t-input-number v-model="formData.stationId" :min="1" /></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="电池 ID" name="batteryId"><t-input-number v-model="formData.batteryId" :min="1" /></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="订单类型" name="orderType"><t-select v-model="formData.orderType"><t-option :value="1" label="换电" /><t-option :value="2" label="暂存" /><t-option :value="3" label="租赁" /></t-select></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="订单状态" name="status"><t-select v-model="formData.status"><t-option :value="1" label="进行中" /><t-option :value="2" label="已完成" /><t-option :value="3" label="异常" /><t-option :value="4" label="已取消" /></t-select></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="实付金额（元）" name="amount"><t-input-number v-model="formData.amount" :min="0" :decimal-places="2" :step="0.01" /></t-form-item></t-col>
    <t-col :xs="12" :lg="6"><t-form-item label="开始时间" name="startTime"><t-date-picker v-model="formData.startTime" style="width: 100%" enable-time-picker allow-input clearable /></t-form-item></t-col>
    <t-col :xs="12" :lg="6"><t-form-item label="结束时间" name="endTime"><t-date-picker v-model="formData.endTime" style="width: 100%" enable-time-picker allow-input clearable /></t-form-item></t-col>
    <t-col :span="12"><t-form-item label="备注" name="remark"><t-textarea v-model="formData.remark" :maxlength="255" placeholder="请输入订单备注" /></t-form-item></t-col>
  </t-row></div></div><div class="form-submit-container"><div class="form-submit-sub"><div class="form-submit-left"><t-button theme="primary" class="form-submit-confirm" type="submit">保存订单</t-button><t-button type="reset" class="form-submit-cancel" theme="default" variant="base">重置</t-button></div></div></div></t-form></t-loading>
</template>
<script lang="ts">export default { name: 'swapOrderEdit' };</script>
<script setup lang="ts">
import type { SubmitContext } from 'tdesign-vue-next'; import type { FormRule } from 'tdesign-vue-next'; import { MessagePlugin } from 'tdesign-vue-next'; import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import ApiSwapOrder from '@/api/energy/ApiSwapOrder'; import router from '@/router'; import { closeOrBack } from '@/utils/url-utils';
const route = useRoute(); const loading = ref(true); const formData = ref<any>({ id: null, orderNo: '', userId: null, stationId: null, batteryId: null, orderType: 1, status: 1, amount: 0, startTime: '', endTime: '', remark: '', createTime: '', updateTime: '' }); const FORM_RULES: Record<string, FormRule[]> = { orderNo: [{ required: true, message: '请输入订单号', trigger: 'blur' }], userId: [{ required: true, number: true, message: '请输入用户 ID', trigger: 'change' }], orderType: [{ required: true, number: true, message: '请选择订单类型', trigger: 'change' }], status: [{ required: true, number: true, message: '请选择订单状态', trigger: 'change' }] };
function onReset() { if (!formData.value.id) Object.assign(formData.value, { orderNo: '', userId: null, stationId: null, batteryId: null, orderType: 1, status: 1, amount: 0, startTime: '', endTime: '', remark: '' }); } function onSubmit(context: SubmitContext) { if (context.validateResult !== true) return; ApiSwapOrder.edit({ data: formData.value, success: () => { MessagePlugin.success('订单已保存'); closeOrBack(route, router); } }); } onMounted(() => { const { id } = route.query; if (!id) { loading.value = false; return; } ApiSwapOrder.detail({ id, success: (res: any) => { formData.value = { ...formData.value, ...res }; loading.value = false; }, fail: () => { loading.value = false; } }); });
</script>
<style lang="less" scoped>.form-tip { margin: -4px 0 20px; color: var(--td-text-color-secondary); }</style>
