<template>
  <t-loading :loading="loading"><t-form class="base-form" :data="formData" :rules="FORM_RULES" label-align="top" :label-width="100" @keydown.enter.prevent @reset="onReset" @submit="onSubmit"><div class="form-basic-container"><div class="form-basic-item"><div class="form-basic-container-title">{{ formData.id ? '编辑换电电池' : '新增换电电池' }}</div><p class="form-tip">电池状态和电量会直接影响小程序站点库存展示。</p><t-row class="row-gap" :gutter="[32, 24]">
    <t-col :xs="12" :lg="6"><t-form-item label="电池编号" name="batteryNo"><t-input v-model="formData.batteryNo" :maxlength="50" placeholder="请输入唯一电池编号" /></t-form-item></t-col>
    <t-col :xs="12" :lg="6"><t-form-item label="所属换电站 ID" name="stationId"><t-input-number v-model="formData.stationId" :min="1" placeholder="请输入换电站 ID" /></t-form-item></t-col>
    <t-col :xs="12" :lg="6"><t-form-item label="电池型号" name="model"><t-input v-model="formData.model" :maxlength="50" placeholder="例如：GX-72V-35Ah" /></t-form-item></t-col>
    <t-col :xs="12" :lg="3"><t-form-item label="电压（V）" name="voltage"><t-input-number v-model="formData.voltage" :min="0" /></t-form-item></t-col>
    <t-col :xs="12" :lg="3"><t-form-item label="容量（Ah）" name="capacity"><t-input-number v-model="formData.capacity" :min="0" /></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="当前电量（%）" name="powerPercent"><t-input-number v-model="formData.powerPercent" :min="0" :max="100" /></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="健康度（%）" name="healthPercent"><t-input-number v-model="formData.healthPercent" :min="0" :max="100" /></t-form-item></t-col>
    <t-col :xs="12" :lg="4"><t-form-item label="电池状态" name="status"><t-select v-model="formData.status"><t-option :value="1" label="可租" /><t-option :value="2" label="使用中" /><t-option :value="3" label="暂存中" /><t-option :value="4" label="维修中" /><t-option :value="0" label="已停用" /></t-select></t-form-item></t-col>
    <t-col :xs="12" :lg="6"><t-form-item label="最近换电时间" name="lastSwapTime"><t-date-picker v-model="formData.lastSwapTime" style="width: 100%" enable-time-picker allow-input clearable /></t-form-item></t-col>
  </t-row></div></div><div class="form-submit-container"><div class="form-submit-sub"><div class="form-submit-left"><t-button theme="primary" class="form-submit-confirm" type="submit">保存电池</t-button><t-button type="reset" class="form-submit-cancel" theme="default" variant="base">重置</t-button></div></div></div></t-form></t-loading>
</template>
<script lang="ts">export default { name: 'swapBatteryEdit' };</script>
<script setup lang="ts">
import type { SubmitContext } from 'tdesign-vue-next'; import type { FormRule } from 'tdesign-vue-next'; import { MessagePlugin } from 'tdesign-vue-next'; import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import ApiSwapBattery from '@/api/energy/ApiSwapBattery'; import router from '@/router'; import { closeOrBack } from '@/utils/url-utils';
const route = useRoute(); const loading = ref(true); const formData = ref<any>({ id: null, batteryNo: '', stationId: null, model: '', voltage: null, capacity: null, powerPercent: 100, healthPercent: 100, status: 1, lastSwapTime: '', createTime: '', updateTime: '' }); const FORM_RULES: Record<string, FormRule[]> = { batteryNo: [{ required: true, message: '请输入电池编号', trigger: 'blur' }], powerPercent: [{ required: true, number: true, message: '请输入当前电量', trigger: 'change' }], healthPercent: [{ required: true, number: true, message: '请输入健康度', trigger: 'change' }], status: [{ required: true, number: true, message: '请选择电池状态', trigger: 'change' }] };
function onReset() { if (!formData.value.id) Object.assign(formData.value, { batteryNo: '', stationId: null, model: '', voltage: null, capacity: null, powerPercent: 100, healthPercent: 100, status: 1, lastSwapTime: '' }); } function onSubmit(context: SubmitContext) { if (context.validateResult !== true) return; ApiSwapBattery.edit({ data: formData.value, success: () => { MessagePlugin.success('电池已保存'); closeOrBack(route, router); } }); } onMounted(() => { const { id } = route.query; if (!id) { loading.value = false; return; } ApiSwapBattery.detail({ id, success: (res: any) => { formData.value = { ...formData.value, ...res }; loading.value = false; }, fail: () => { loading.value = false; } }); });
</script>
<style lang="less" scoped>.form-tip { margin: -4px 0 20px; color: var(--td-text-color-secondary); }</style>
