name: app
description: "IC framework Flutter app project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.0.1
  json_annotation: ^4.9.0
  event_bus: ^2.0.0
  web_socket_channel: ^3.0.1
  cupertino_icons: ^1.0.6
  oktoast: ^3.4.0
  jwt_decoder: ^2.0.1
  cookie_jar: ^4.0.8
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  provider: ^6.0.5
  flutter_echarts: ^2.5.0
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  package_info_plus: ^8.1.3
  device_info_plus: ^11.2.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/svg/
    - assets/svg/chat/
    - assets/svg/big/
    - assets/svg/icons/
    - assets/version_date
